# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-report-generator:
    build:
      target: development
    image: ffc-pay-report-generator-development
    container_name: ffc-pay-report-generator-development
    ports:
      - "9290:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-pay-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10090:10000"
      - "10091:10001"
      - "10092:10002"

volumes:
  azurite_data:
