const {
  PAYMENT_EXTRACTED,
  PAYMENT_ENRICHED,
  PAYMENT_PAUSED_DEBT,
  PAYMENT_DEBT_ATTACHED,
  PAYMENT_PAUSED_LEDGER,
  PAYMENT_LEDGER_ASSIGNED,
  PAYMENT_PAUSED_QUALITY_CHECK,
  PAYMENT_FAILED_QUALITY_CHECK,
  PAYMENT_PASSED_QUALITY_CHECK,
  PAYMENT_PROCESSED,
  PAYMENT_SUBMITTED,
  PAYMENT_ACKNOWLEDGED,
  PAYMENT_SETTLED
} = require('../../constants/events')
const {
  PAYMENT_EXTRACTED_STATUS,
  PAYMENT_ENRICHED_STATUS,
  PAYMENT_PAUSED_DEBT_STATUS,
  PAYMENT_DEBT_ATTACHED_STATUS,
  PAYMENT_PAUSED_LEDGER_STATUS,
  PAYMENT_LEDGER_ASSIGNED_STATUS,
  PAYMENT_PAUSED_QUALITY_CHECK_STATUS,
  PAYMENT_FAILED_QUALITY_CHECK_STATUS,
  PAYMENT_PASSED_QUALITY_CHECK_STATUS,
  PAYMENT_PROCESSED_STATUS,
  PAYMENT_SUBMITTED_STATUS,
  PAYMENT_ACKNOWLEDGED_STATUS,
  PAYMENT_SETTLED_STATUS
} = require('../../constants/statuses')

const getStatus = (events) => {
  const eventMap = {}
  eventMap[PAYMENT_EXTRACTED] = PAYMENT_EXTRACTED_STATUS
  eventMap[PAYMENT_ENRICHED] = PAYMENT_ENRICHED_STATUS
  eventMap[PAYMENT_PAUSED_DEBT] = PAYMENT_PAUSED_DEBT_STATUS
  eventMap[PAYMENT_DEBT_ATTACHED] = PAYMENT_DEBT_ATTACHED_STATUS
  eventMap[PAYMENT_PAUSED_LEDGER] = PAYMENT_PAUSED_LEDGER_STATUS
  eventMap[PAYMENT_LEDGER_ASSIGNED] = PAYMENT_LEDGER_ASSIGNED_STATUS
  eventMap[PAYMENT_PAUSED_QUALITY_CHECK] = PAYMENT_PAUSED_QUALITY_CHECK_STATUS
  eventMap[PAYMENT_FAILED_QUALITY_CHECK] = PAYMENT_FAILED_QUALITY_CHECK_STATUS
  eventMap[PAYMENT_PASSED_QUALITY_CHECK] = PAYMENT_PASSED_QUALITY_CHECK_STATUS
  eventMap[PAYMENT_PROCESSED] = PAYMENT_PROCESSED_STATUS
  eventMap[PAYMENT_SUBMITTED] = PAYMENT_SUBMITTED_STATUS
  eventMap[PAYMENT_ACKNOWLEDGED] = PAYMENT_ACKNOWLEDGED_STATUS
  eventMap[PAYMENT_SETTLED] = PAYMENT_SETTLED_STATUS
  const lastEvent = events[events.length - 1]
  return eventMap[lastEvent.type]
}

module.exports = {
  getStatus
}
