{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-report-generator.container-secret") -}}
{{- define "ffc-pay-report-generator.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
