---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  azureStorageAccountName: prdffcpayst1001
  endpointEnabled: true
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-report-generator
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appinsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING