const {
  PAYMENT_EXTRACTED,
  PAYMENT_ENRICHED,
  PAYMENT_PAUSED_CROSS_BORDER,
  PAYMENT_PAUSED_DEBT,
  PAYMENT_DEBT_ATTACHED,
  PAYMENT_PAUSED_LEDGER,
  PAYMENT_LEDGER_ASSIGNED,
  PAYMENT_PAUSED_QUALITY_CHECK,
  PAYMENT_QUALITY_CHECK_FAILED,
  PAYMENT_QUALITY_CHECK_PASSED,
  PAYMENT_RESET,
  PAYMENT_SUPPRESSED,
  PAYMENT_PROCESSED,
  PAYMENT_SUBMITTED,
  PAYMENT_ACKNOWLEDGED,
  PAYMENT_SETTLED
} = require('../../../../app/constants/events')

const { getEventOrder } = require('../../../../app/reports/shared/get-event-order')

const cases = [
  [PAYMENT_EXTRACTED, 1],
  [PAYMENT_ENRICHED, 2],
  [PAYMENT_PAUSED_CROSS_BORDER, 3],
  [PAYMENT_PAUSED_DEBT, 4],
  [PAYMENT_DEBT_ATTACHED, 5],
  [PAYMENT_PAUSED_LEDGER, 6],
  [PAYMENT_LEDGER_ASSIGNED, 7],
  [PAYMENT_PAUSED_QUALITY_CHECK, 8],
  [PAYMENT_QUALITY_CHECK_FAILED, 9],
  [PAYMENT_QUALITY_CHECK_PASSED, 10],
  [PAYMENT_RESET, 11],
  [PAYMENT_SUPPRESSED, 12],
  [PAYMENT_PROCESSED, 13],
  [PAYMENT_SUBMITTED, 14],
  [PAYMENT_ACKNOWLEDGED, 15],
  [PAYMENT_SETTLED, 16]
]

describe('get event order', () => {
  test.each(cases)('returns %s → %i', (event, expected) => {
    expect(getEventOrder(event)).toBe(expected)
  })
})
